In [15]:
import numpy as np

dataset_input = np.load('D:/Dataset_1/input.npy', allow_pickle=True) 
dataset_output = np.load('D:/Dataset_1/output.npy', allow_pickle=True) 
print(dataset_input)
print(dataset_output)

[[3 3 6 ... 4 1 6]
 [1 2 2 ... 3 6 3]
 [3 8 3 ... 1 1 3]
 ...
 [1 8 1 ... 1 6 2]
 [3 1 3 ... 9 2 9]
 [2 1 3 ... 3 1 2]]
[[3 3 0 ... 9 4 7]
 [1 2 0 ... 4 6 7]
 [3 8 0 ... 1 7 7]
 ...
 [1 8 0 ... 4 8 7]
 [3 1 0 ... 8 1 7]
 [2 1 0 ... 9 7 7]]


In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dataset_input, dataset_output, test_size=0.2, random_state=1)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(1600, 200)
(1600, 500)
(400, 200)
(400, 500)


In [3]:
type(X_train)

numpy.ndarray

In [23]:
from keras.layers import Input, Dense
from keras.models import Model

def create_dense_ae():
    # Dimension of coded representation
    encoding_dim = 200

    # Encoder
    # Input placeholder
    input_element = Input(shape=200) # 1, 200, 1 - dimensions of strings, cloumns and filters of one sample element
    # Representation coded with fully connected layer
    encoded = Dense(encoding_dim, activation='relu')(input_element)
    
    # Decoder
    # Representation uncoded with another fully connected layer
    input_encoded = Input(shape=(encoding_dim,))
    decoded = Dense(1*500, activation='sigmoid')(input_encoded)

    # Model(input_layer, output_layer)
    # Model(model_1, model_2)
    encoder = Model(input_element, encoded, name="encoder")
    decoder = Model(input_encoded, decoded, name="decoder")
    autoencoder = Model(input_element, decoder(encoder(input_element)), name="autoencoder")
    return encoder, decoder, autoencoder

In [24]:
encoder, decoder, autoencoder = create_dense_ae()
autoencoder.compile(optimizer='adam', loss='binary_crossentropy')

In [25]:
autoencoder.summary()

Model: "autoencoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         [(None, 200)]             0         
_________________________________________________________________
encoder (Functional)         (None, 200)               40200     
_________________________________________________________________
decoder (Functional)         (None, 500)               100500    
Total params: 140,700
Trainable params: 140,700
Non-trainable params: 0
_________________________________________________________________


In [26]:
autoencoder.fit(X_train, y_train,
                epochs=50,
                batch_size=100,
                shuffle=False,
                validation_data=(X_test, y_test))

Epoch 1/50
16/16 [==============================] - 0s 13ms/step - loss: -12.0821 - val_loss: -41.7134
Epoch 2/50
16/16 [==============================] - 0s 5ms/step - loss: -110.7796 - val_loss: -222.2404
Epoch 3/50
16/16 [==============================] - 0s 5ms/step - loss: -388.8164 - val_loss: -624.0000
Epoch 4/50
16/16 [==============================] - 0s 5ms/step - loss: -915.4444 - val_loss: -1301.2582
Epoch 5/50
16/16 [==============================] - 0s 6ms/step - loss: -1733.0642 - val_loss: -2284.3914
Epoch 6/50
16/16 [==============================] - 0s 5ms/step - loss: -2864.0540 - val_loss: -3588.6826
Epoch 7/50
16/16 [==============================] - 0s 5ms/step - loss: -4319.8589 - val_loss: -5221.6714
Epoch 8/50
16/16 [==============================] - 0s 6ms/step - loss: -6104.8364 - val_loss: -7184.7051
Epoch 9/50
16/16 [==============================] - 0s 6ms/step - loss: -8219.6611 - val_loss: -9478.7412
Epoch 10/50
16/16 [==============================] - 0