### Data Generation

In [1]:
import random
from typing import Tuple, List

import numpy as np

from Base.bp2DState import State
from Base.bp2DBox import Box
from Base.bpReadWrite import ReadWrite
from Base.bp2DPnt import Point
from Base.bpStateGenerators import sliced_box_state_generator

import csv

In [2]:
def output(state_from_sliced_box_state_generator, filename='D:/Dataset_1/buf.csv'):
    state = []
    with open(filename) as csvfile:
        file = csv.reader(csvfile)
        for row in file:
            state.append(row)
    # print(state)
    out = []
    for k in range(15,len(state)):
        for z in range(5):
            buf = int(state[k][0].split()[z])
            out.append(buf)
    # print(output)
    return out   

In [3]:
def unsolve_state(state, shuffle=True):
    boxes = state.boxes_open + [box for bin in state.bins for box in bin.boxes_stored]
    if shuffle:
        random.shuffle(boxes)
    new_boxes = [Box(box.w, box.h) for box in boxes]
    return State(1, state.bin_size, new_boxes)

In [4]:
def inp(state_unsolved):
    inputt = []
    for k in range(len(state_unsolved.boxes_open)):
        width = state_unsolved.boxes_open[k].w
        height = state_unsolved.boxes_open[k].h
        inputt.append(width)
        inputt.append(height)
    # print(type(inputt))
    return inputt

In [7]:
def dataset_generation(num_samples, binnum=8, boxnum=100, 
                       boxwidthmin=1, boxwidthmax=4,
                       boxheightmin=1, boxheightmax=4,
                       filepath='D:/Dataset_1/'):
    input_file = []
    output_file = []
    
    for k in range(num_samples):
        state = sliced_box_state_generator((10,10), bin_num=binnum, box_num=boxnum, peel_area=100,
                          box_width_min=boxwidthmin, box_width_max=boxwidthmax,
                          box_height_min=boxheightmin, box_height_max=boxheightmax,
                                          path='D:/Dataset_1/buf.csv')
        out = output(state)
        output_file.append(out)
        
        state_unsolved = unsolve_state(state, shuffle=False)
        inp_ = inp(state_unsolved)
        input_file.append(inp_)
        
    output_file = np.array(output_file)
    input_file = np.array(input_file)
    np.save(filepath+'input.npy', input_file)
    np.save(filepath+'output.npy', output_file)
    return output_file, input_file

In [10]:
[output_file, input_file] = dataset_generation(100)

In [11]:
dataset_input = np.load('D:/Dataset_1/input.npy', allow_pickle=True) 
dataset_output = np.load('D:/Dataset_1/output.npy', allow_pickle=True) 
print(dataset_input)
print(dataset_output)

[[3 2 1 ... 2 1 2]
 [5 2 3 ... 6 1 6]
 [1 9 1 ... 4 2 2]
 ...
 [2 1 1 ... 4 2 3]
 [1 1 1 ... 1 1 1]
 [2 1 1 ... 1 3 1]]
[[3 2 0 ... 8 8 7]
 [5 2 0 ... 9 4 7]
 [1 9 0 ... 7 8 7]
 ...
 [2 1 0 ... 8 6 7]
 [1 1 0 ... 9 9 7]
 [2 1 0 ... 7 9 7]]
